DistribuidoraOccidentalPy/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views


from django.conf.urls.static import static
from django.conf import settings 

from core.views import VistaListaProductos

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('profile/<int:id>/', views.profile, name='profile'),

    path('login/',views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.registro, name='registro'),
    path('ordenar/', views.ordenar, name='ordenar'),
    path('carro/', include('carrito.urls')),
    path('carro/',views.login_view, name='carro'),
    path('tienda/', VistaListaProductos.as_view(), name='tienda'),
    path('productos/', include('core.urls')),
    path('edit_profile/', views.UpdateUserView.as_view(), name="edit_user"),
    # ruta PQRS 
    path('PQRS/',views.ver_pqrs, name='pqrs'),
    path('subir_pqr/',views.añadir_pqrs, name='subir_pqr'),
    path('direcciones/', include('direcciones.urls')),
    path('orden/', include('orden.urls')),
    path('inventario/', include('inventario.urls')),
    path('correo/', include('correo.urls')),
    path('buscar/', views.buscar_productos, name='buscar'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset_password_complete/', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_complete'),
    path('accounts/login/',views.login_view, name='accounts_login'),









]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>', views.VistaDetalleProducto.as_view(), name='producto'),

]

orden/urls.py
from django.urls import path

from . import views

app_name = "orden"

urlpatterns = [
     path('', views.orden, name='orden'),
     path('direccion', views.address, name='direccion'),
     path('seleccionar/direccion', views.select_address, name='seleccionar'),
     path('establecer/direccion/<int:pk>', views.check_address, name='check_direccion'),
     path('confirmacion', views.confirm, name='confirmar'),
     path('cancelar', views.cancel, name='cancelar'),
     path('completar', views.complete, name='completar'),
     path('completadas', views.VistaOrdenLista.as_view(), name='completadas')
]

templates/incluidos/dash.html
<nav class="list-group">
    {% if not user.is_staff %}
    <a class="list-group-item" href="#"> Account overview  </a>
    <a class="list-group-item" href="{{ direcciones }}"> Direcciones  </a>
    <a class="list-group-item" href="{% url 'pqrs'%}">Mis PQRS</a>
    <a class="list-group-item" href="{% url 'orden:completadas' %}"> Mis compras </a>
    <a class="list-group-item active" href="{% url 'profile' id=user.id %}"> Configuracion </a>
                
    {% else %}
    <a class="list-group-item" href="{% url 'productosbajos'%}">Productos bajos de Stock</a>
    <a class="list-group-item" href="{% url 'registrar_transaccion'%}">Transaccion</a>
    <a class="list-group-item" href="{% url 'reporte_movimientos_inventario'%}"> Reporte de Inventario  </a>
    <a class="list-group-item" href="{% url 'enviar_correos' %}" >Enviar correos</a>	
    <a class="list-group-item" href="{% url 'admin:index' %}" >Panel de administacion</a>	
			
    {% endif %}
    <a class="list-group-item" href="{% url 'logout'%}">Cerrar sesion</a>
</nav>

templates/incluidos/footer.html
{% load static %}

<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> 2023 Distribuidora Occidental </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">DistribuidoraOccidental@gmail.com</span>
				<span  class="px-2">+57 3005118279</span>
				<span  class="px-2">Kennedy</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-paypal"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/incluidos/header.html
{% load static %}
  <header class="section-header">
      <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
      <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div> <!-- container //  -->
      </nav>
      <section class="header-main border-bottom">
        <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-2 col-md-3 col-6">
          <a href="{% url 'index'%}" class="brand-wrap">
            <img  src="{% static 'img/images/logo.png'%}" width="79" height="80" >
          </a> <!-- brand-wrap.// -->
        </div>
        <div class="col-lg col-sm col-md col-6 flex-grow-0">
         <!-- category-wrap.// -->
        </div> <!-- col.// -->
        <div class="col-lg  col-md-6 col-sm-12 col">
          <form action="#" class="search">
            <div class="input-group w-100">
                <div class="input-group-append">
                </div>
              </div>
          </form> <!-- search-wrap .end// -->
        </div> <!-- col.// -->
        <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
              <div class="d-flex justify-content-end mb-3 mb-lg-0">
                <div class="widget-header">
                 <h6 class="title text-muted">BIENVENIDO</h6>
                  <div> 
                    {% if user.is_authenticated %}
                    <a href="{% url 'profile' id=user.id %}" >{{ user.first_name}} {{ user.primer_apellido}}</a> <span class="dark-transp"> </span>
                    {% else %}
                    <a href="{% url 'login'%}">Ingresa</a> <span class="dark-transp"> </span>
                    {% endif %}
                  </div>
                </div>
                <a href="{% url 'carro'%}" class="widget-header pl-3 ml-3">
                  <div class="icon icon-sm rounded-circle border"><i class="fas fa-cart-plus"></i></div>
                  <span class="badge badge-pill badge-danger notify"></span>
                </a>
              </div> <!-- widgets-wrap.// -->
            </div> <!-- col.// -->
      </div> <!-- row.// -->
        </div> <!-- container.// -->
      </section> <!-- header-main .// -->
</header> <!-- section-header.// -->

{% block js %}
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/script.js'%}" type="text/javascript"></script>
{% endblock %}

templates/incluidos/messages.html
{% if messages %}
  <div class="alert alert-info alert-fixed" role="alert">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  </div>
{% endif %}