DistribuidoraOccidentalPy/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views


from django.conf.urls.static import static
from django.conf import settings 

from core.views import VistaListaProductos

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('profile/<int:id>/', views.profile, name='profile'),

    path('login/',views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.registro, name='registro'),
    path('ordenar/', views.ordenar, name='ordenar'),
    path('carro/', include('carrito.urls')),
    path('carro/',views.login_view, name='carro'),
    path('tienda/', VistaListaProductos.as_view(), name='tienda'),
    path('productos/', include('core.urls')),
    path('edit_profile/', views.UpdateUserView.as_view(), name="edit_user"),
    # ruta PQRS 
    path('PQRS/',views.ver_pqrs, name='pqrs'),
    path('subir_pqr/',views.añadir_pqrs, name='subir_pqr'),
    path('direcciones/', include('direcciones.urls')),
    path('orden/', include('orden.urls')),
    path('inventario/', include('inventario.urls')),
    path('correo/', include('correo.urls')),
    path('buscar/', views.buscar_productos, name='buscar'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset_password_complete/', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_complete'),
    path('accounts/login/',views.login_view, name='accounts_login'),









]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>', views.VistaDetalleProducto.as_view(), name='producto'),

]

direcciones/urls.py
from django.urls import path
from . import views

app_name = 'direcciones'

urlpatterns = [

    path('',views.DireccionesEnvioView.as_view(),name='direcciones'),
    path('nuevo',views.create,name='create'),
    path('editar/<int:pk>',views.DireccionesEnvioUpdate.as_view(),name='update'),
    path('default/<int:pk>',views.default,name='default'),



]

orden/urls.py
from django.urls import path

from . import views

app_name = "orden"

urlpatterns = [
     path('', views.orden, name='orden'),
     path('direccion', views.address, name='direccion'),
     path('seleccionar/direccion', views.select_address, name='seleccionar'),
     path('establecer/direccion/<int:pk>', views.check_address, name='check_direccion'),
     path('confirmacion', views.confirm, name='confirmar'),
     path('cancelar', views.cancel, name='cancelar'),
     path('completar', views.complete, name='completar'),
     path('completadas', views.VistaOrdenLista.as_view(), name='completadas')
]

direcciones/models.py
from django.db import models
from usuario.models import User

class DirrecionesEnvios(models.Model):
    user = models.ForeignKey(User,null=False,blank=False, on_delete=models.CASCADE)
    direccion = models.CharField(max_length=200)
    localidad = models.CharField(max_length=100,null=False,blank=False)
    barrio = models.CharField(max_length=100)
    default = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.direccion
    
    @classmethod
    def set_default_false(self, user):
        DirrecionesEnvios.objects.filter(user=user).filter(default=True).update(default=False)

    def set_default(self):
        self.default = True
        self.save()   
         
    class Meta:
        verbose_name = 'Dirrecion de Envio'
        verbose_name_plural = 'Dirreciones de Envios'
        db_table = 'DirrecionesEnvios'

    @property
    def direcccionFull(self):
        return '{} - {} - {}'.format(self.direccion,self.localidad,self.barrio)

direcciones/forms.py
from django.forms import ModelForm
from .models import DirrecionesEnvios


class DireccionesForm(ModelForm):
    class Meta:
        model = DirrecionesEnvios
        fields = [
            'direccion', 'localidad', 'barrio'
        ]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields['direccion'].widget.attrs.update({
            'class': 'form-control'
        })

direcciones/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import DirrecionesEnvios
from django.views.generic import ListView
from django.views.generic.edit import UpdateView
from .forms import DireccionesForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from orden.utils import crear_obtener_orden
from carrito.utils import crear_obtener_carrito

class DireccionesEnvioView(LoginRequiredMixin,ListView):
    login_url = 'login'
    model = DirrecionesEnvios
    template_name = 'direcciones/dirreccionesEnvio.html'

    def get_queryset(self):
        return DirrecionesEnvios.objects.filter(user=self.request.user).order_by('-default')
    
class DireccionesEnvioUpdate(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    login_url = 'login'
    model = DirrecionesEnvios
    form_class = DireccionesForm
    template_name = 'direcciones/update.html'
    success_message = 'Direccion actualizada'

    def dispatch(self, request, *args, **kwargs):
        if request.user.id != self.get_object().user_id:
            return redirect('carrito:carro')

        return super(DireccionesEnvioUpdate, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('direcciones:direcciones', kwargs={
            #'pk': self.object.pk
        })



@login_required(login_url='login')
def create(request):
    form = DireccionesForm(request.POST or None)

    if request.method == 'POST' and form.is_valid():
        direcciones = form.save(commit=False)
        direcciones.user = request.user
        direcciones.default = not  DirrecionesEnvios.objects.filter(user=request.user).exists()

        direcciones.save()

        if request.GET.get('next'):
            if request.GET['next'] == reverse('orden:direccion'):
                carrito= crear_obtener_carrito(request)
                orden = crear_obtener_orden(carrito,request)

                orden.update_shipping_direccion(direcciones)
                return HttpResponseRedirect(request.GET['next'])

        messages.success(request, 'Direccion creada exitosamente')
        return redirect('direcciones:direcciones')

    return render(request,'direcciones/agregarDireccion.html', {
        'form': form
    })

@login_required(login_url='login')
def default(request, pk):
    direcciones = get_object_or_404(DirrecionesEnvios, pk=pk)

    if request.user.id != direcciones.user_id:
        return redirect('carrito:carro')
    DirrecionesEnvios.set_default_false(request.user)
    direcciones.set_default()

    messages.success(request, 'Dirección principal actualizada')

    return redirect('direcciones:direcciones')

templates/ordenes/confirmar.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
      <div class="col-8">
        <div class="h3"> 
          Confirma tu pedido
        </div>
        
        <div class="card">
          <div class="card-body">
            <div class="row"> 
              <div class="col-4"> 
                <div class="font-weight-bold">
                  Direccion de Envio
                </div>
                <div class="cart-text">
                  {{direccionorden.direccion}}
                </div>
                <div class="cart-text">
                  {{direccionorden.localidad}}
                </div>
                <div class="cart-text">
                  {{direccionorden.barrio}}
                </div>
              </div>
            </div>          
          </div>    
        </div>
        
        <div class="mt-3">
          <div class="card">
            <div class="card-body">
              {% for producto in carrito.productos.all %}
                {% include 'ordenes/snippets/productosorden.html' %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      
      <div class="col-4">
        <br>
        <br>
        <div id="smart-button-container">
          <div style="text-align: center;">
            <div id="paypal-button-container"></div>
          </div>
        </div>
      </div>
    </div>
  </div>

  
<div class="col mt-2">
    {% url 'orden:completar' as next_url %}
    <div class="">
        <hr>
        <div class="font-weight-bold text-danger">
            Total (Impuestos incluidos)
            <div class="d-inline-block">
                    {{ orden.total }}
            </div>
        </div>
    </div>
    <div class="mt-2">
        <button  class="btn btn-warning" id="pedidoauuu" disabled hidden>
            <a href="{{ next_url }}">Confirmar pedido</a>
        </button>
    </div>
    <div class="mt-2">
        <a href="{% url 'orden:cancelar' %}" class="btn btn-danger" disabled="true">Cancelar Orden</a>
    </div>
</div>



<script src="https://www.paypal.com/sdk/js?client-id=sb&enable-funding=venmo&currency=USD" data-sdk-integration-source="button-factory"></script>
<script>
    const confirmarPedido = document.getElementById('pedidoauuu');

// Deshabilita el botón "Confirmar pedido" inicialmente
confirmarPedido.disabled = true;
confirmarPedido.hidden= true;
  function initPayPalButton() 
  {
    paypal.Buttons({
      style: {
        shape: 'rect',
        color: 'gold',
        layout: 'vertical',
        label: 'paypal',

      },

      createOrder: function(data, actions) {
        return actions.order.create({
          purchase_units: [{
            amount:{
            value: '{{orden.total}}'
        }
    }]
        });
      },

      onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {

            // Full available details
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));

            // Show a success message within this page, e.g.
            const element = document.getElementById('paypal-button-container');
            element.innerHTML = '';
            element.innerHTML = '<h3>Thank you for your payment!</h3>';
            // Or go to another URL:  actions.redirect('thank_you.html');
                    // Habilita el botón "Confirmar pedido"
            confirmarPedido.disabled = false;
            confirmarPedido.hidden = false;
            window.location.href = '{{ next_url }}';


          });
        },

        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();

</script>



{% endblock %}

templates/ordenes/direcciones.html
{% extends 'base.html'%}

{% block content %}

<div class="col">
    {% if direcciones %}
      <div class="h3">
        Recoge el pedido en el punto de entrega.
      </div>
      <div class="">
        {% include 'direcciones/snippets/direcciones.html' %} 

        <div class="mt-2"> 
          <a href="{% url 'orden:confirmar' %}" class="btn btn-warning"> Entregar a esta direccion</a>
        </div>

        <div class="mt-2"> 
          <a href="{% url 'orden:seleccionar' %}">Elige otra direccion</a>
        </div>
      </div>

    {% else %}
      <div class="h3">
        Registra tu dirección de envío
      </div>       
      <div class="">
        {% url 'orden:direccion' as next_url %}
        <a href="{% url 'direcciones:create' %}?next={{ next_url }}">Nueva dirección</a>
      </div>
    {% endif %}
  </div>
{% endblock %}

templates/ordenes/ordenar.html
{% extends 'base.html' %}


{% block content %}
<!-- ========================= SECTION CONTENT ========================= -->
<div class="col"> 
    <h2>Revisa tu pedido</h2>
</div>
<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <main class="col-md-9">
    <div class="card">
    
    {% for producto in carrito.productos.all %}
      {% include 'ordenes/snippets/productosorden.html' %}
    {% endfor %}
	
    </div> <!-- card.// -->

    
        </main> <!-- col.// -->
        <aside class="col-md-3">
            {% url 'orden:direccion' as next_url %}
            {% include 'ordenes/snippets/resumen.html' with next_url=next_url %}
        </aside> <!-- col.// -->
    </div>
    
    </div> <!-- container .//  -->
    </section>
    <!-- ========================= SECTION CONTENT END// ========================= -->
      

{% endblock %}

templates/ordenes/ordenes.html
{% extends 'base.html' %}

{% block content %}
<div class="col">
    <div class="h3">
     Mis pedidos
    </div>
    <div>
        {% for orden in object_list %}
            {% include 'ordenes/snippets/orden.html' %}
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/ordenes/resumen.html
<div class="card">
    <div card="card-body">
        <div class="font-weight-bold">
            Resumen del pedido
        </div>
        <div class="">
            <table class="table table-borderless table-sm">
                <thead>
                    <tr>
                        <th scope="col"> </th>
                        <th scope="col"> </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Productos:</td>
                        <td>{{ carrito.total }}</td>
                    </tr>
                    <tr>
                        <td>Envio:</td>
                        <td>{{ orden.precio_envio}}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="">
            <hr>
            <div class="font-weight-bold text-danger">
                Total (Impuestos incluidos)
                <div class="d-inline-block">
                        {{ orden.total }}
                </div>
            </div>
        </div>
    </div>   
</div>

templates/ordenes/select_direccion.html
{% extends 'base.html' %}


{% block content %}

<div class="col">
    <p class="h3">Selecciona una dirección de envío</p>
  
    {% for direcciones in direcciones %}
      <div class="card mb-2">
        <div class="card-body">
          <h5 class="card-title">{{direcciones.direccion}}</h5>
          <p class="card-text">{{ direcciones.localidad }} - {{direcciones.barrio}}</p>
          <a href="{% url 'orden:check_direccion' pk=direcciones.pk %}" class="btn btn-warning">Seleccionar</a>
        </div>
      </div>
    {% endfor %}
  
  </div>

{% endblock %}