DistribuidoraOccidentalPy/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views


from django.conf.urls.static import static
from django.conf import settings 

from core.views import VistaListaProductos

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('profile/<int:id>/', views.profile, name='profile'),

    path('login/',views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('registro/', views.registro, name='registro'),
    path('ordenar/', views.ordenar, name='ordenar'),
    path('carro/', include('carrito.urls')),
    path('carro/',views.login_view, name='carro'),
    path('tienda/', VistaListaProductos.as_view(), name='tienda'),
    path('productos/', include('core.urls')),
    path('edit_profile/', views.UpdateUserView.as_view(), name="edit_user"),
    # ruta PQRS 
    path('PQRS/',views.ver_pqrs, name='pqrs'),
    path('subir_pqr/',views.añadir_pqrs, name='subir_pqr'),
    path('direcciones/', include('direcciones.urls')),
    path('orden/', include('orden.urls')),
    path('inventario/', include('inventario.urls')),
    path('correo/', include('correo.urls')),
    path('buscar/', views.buscar_productos, name='buscar'),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset_password_send/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('reset_password_complete/', auth_views.PasswordChangeDoneView.as_view(), name='password_reset_complete'),
    path('accounts/login/',views.login_view, name='accounts_login'),









]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carrito/urls.py
from django.urls import path
from . import views

app_name = 'carrito'

urlpatterns = [
    path('', views.carro, name='carro'),
    path('agregar', views.agregar, name='agregar'),
    path('eliminar', views.eliminar, name='eliminar')
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<slug:slug>', views.VistaDetalleProducto.as_view(), name='producto'),

]

direcciones/urls.py
from django.urls import path
from . import views

app_name = 'direcciones'

urlpatterns = [

    path('',views.DireccionesEnvioView.as_view(),name='direcciones'),
    path('nuevo',views.create,name='create'),
    path('editar/<int:pk>',views.DireccionesEnvioUpdate.as_view(),name='update'),
    path('default/<int:pk>',views.default,name='default'),



]

orden/urls.py
from django.urls import path

from . import views

app_name = "orden"

urlpatterns = [
     path('', views.orden, name='orden'),
     path('direccion', views.address, name='direccion'),
     path('seleccionar/direccion', views.select_address, name='seleccionar'),
     path('establecer/direccion/<int:pk>', views.check_address, name='check_direccion'),
     path('confirmacion', views.confirm, name='confirmar'),
     path('cancelar', views.cancel, name='cancelar'),
     path('completar', views.complete, name='completar'),
     path('completadas', views.VistaOrdenLista.as_view(), name='completadas')
]

templates/base.html
{% load static %}

<!DOCTYPE HTML>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'img/images/logoDisc.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.2.1/chart.min.js" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.2.1/dist/chart.umd.min.js"></script>
    
    {% comment %} index styles {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/index/index.css'%}" >
    <link rel="stylesheet" href="{% static 'css/index/bootstrap.css' %}" >
    <link rel="stylesheet" href="{% static 'css/index/boostrap-utilities.css' %}" >
    <link rel="stylesheet" href="{% static 'css/index/boostrap-reboot.css' %}" >
    <link rel="stylesheet" href="{% static 'css/index/boostrap-grid.css' %}" >
    
    {% comment %} tienda styles {% endcomment %}
    <link  href="{% static 'img/images/logoDisc.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link href="{% static 'css/tienda/bootstrap.css'%}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'fonts/fontawesome/css/all.min.css'%}" type="text/css" rel="stylesheet">
    <link href="{% static 'css/tienda/ui.css'%}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/tienda/responsive.css'%}" rel="stylesheet" media="only screen and (max-width: 1200px)" />

    {% comment %} profile styles {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/profile/bootstrap.css' %}" >
    <link rel="stylesheet" href="{% static 'css/profile/ui.css' %}" >
    <link rel="stylesheet" href="{% static 'css/profile/responsive.css' %}" >
    <link rel="stylesheet" href="{% static 'css/profile/all.min.css' %}" >
    <link rel="stylesheet" href="{% static 'js/profile/script.min.css' %}" >
    <link rel="stylesheet" href="{% static 'css/profile/jquery-2.min.css' %}" >


    {% comment %} js {% endcomment %}
    <script src="{% static 'js/script.js'%}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-2.0.0.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js'%}" type="text/javascript"></script>

    <title>Distribuidora Occidental</title>

</head>
<body>
    {% include 'incluidos/header.html' %}
    {% block content %}
    {% endblock %}
    {% include 'incluidos/footer.html' %}
</body>
</html>

templates/carro.html
{% load static %}
{% load producto_extras %}

{% if carrito.productos.exists %}
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Imagen</th>
                <th scope="col">Producto</th>
                <th scope="col">Cantidad</th>
                <th scope="col">Precio</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for cp in carrito.products_related.all %}
                {% with producto=cp.producto %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {% if producto.Foto %}
                                <img src="{{ producto.Foto.url }}" alt="Imagen del producto" class="img-thumbnail">
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'producto' producto.slug %}">{{ producto.NombreProducto }}</a>
                            {% include 'carrito/eliminar.html' %}
                        </td>
                        <td>{{ cp.cantidad }}</td>
                        <td><span class="font-weight-bold">{{ producto.precio }}</span></td>
                        <td>
                            {% include 'carrito/eliminar.html' %}
                        </td>
                    </tr>
                {% endwith %}
            {% endfor %}
        </tbody>
    </table>
</div>

{% if carrito.products_related.all %}
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <div class="font-weight-bold">
                    Subtotal ({{ carrito.productos.count }}): <span class="text-danger">{{ carrito.subtotal }}</span>
                </div>
                <div class="mt-2">
                    <a href="{% url 'orden:orden'%}" class="btn btn-warning btn-block">Proceder al pago</a>
                </div>
            </div>
        </div>
    </div>
{% else %}
    <div class="col-12">
        <p class="h3">Tu carrito de compras esta vacio.</p>
        <a href="{% url 'tienda' %}" class="btn btn-primary">Seguir comprando</a>
    </div>
{% endif %}

templates/index.html
{% load static %}
{% url 'direcciones:direcciones' as direcciones %}

<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  href="{% static 'img/images/logoDisc.ico' %}" rel="shortcut icon" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/index/index.css'%}" >
    <link rel="stylesheet" href="{% static 'css/index/bootstrap.css' %}" >
    <link href="{% static 'fonts/fontawesome/css/all.min.css'%}" type="text/css" rel="stylesheet">
    <title>Distribuidora Occidental</title>
</head>

<body>
    <header class="xd">
        <nav class="navegacion">  
            <a href="#" class="logo"> <img src="{% static 'img/images/logo.png'%}" alt=""></img>
            </a>
            <ul class="menu">
                <li><a href="{% url 'tienda' %}">Tienda</a></li>
                <li class="nav-item"><a href="{% url 'carrito:carro' %}">Carrito</a></li>
                <li><a href="#">Nosotros</a></li>
                <li><a href="#">Servicios</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'profile' id=user.id %}">Mi cuenta</a></li>
                {% endif %}

                {% if not  user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'login' %}">Ingresar</a></li>    
                {% else %}
                
                {% endif %}
            </ul>
        </nav>
    </header>

    {% block content %}
    <div class="servicios" id="servicios">
        <h4 class="textServicios">SERVICIOS</h4>
        <h4 class="textVentajas">Nuestras ventajas</h4>
        <div class="serviciosicons">
            <div>
                <ul>
                    <li class="iconsServ"><i class="fas fa-cart-arrow-down fa-6x"></i>
                      <h3>E-Commerce</h3>
                      <p aling="scale">Estamos expandiéndonos a <br></br>la a Web, con un comercio electrónico.</p>
                    </li>

                    <li class="iconsServ"><i class="fas fa-truck fa-6x"></i>
                      <h3>Domicilios</h3>
                      <p aling="scale">Podras realizar tus pedidos <br></br>y nosostros nos encargamos enviarlos <br></br>a tu domicilio en toda Bogotá.</p>
                    </li>

                    <li class="iconsServ"><i class="fas fa-lock fa-6x"></i>
                      <h3>Seguridad-Web</h3>
                      <p aling="scale">Tus datos estaran seguros <br></br>en nuestra página Web :).</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="timeline-container">
      <div class="timeline">
        <img src="{% static 'img/timeline.png' %}" alt="">
      </div>
    </div>
    <!--SCRIPT-->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
    <script src="https://unpkg.com/typewriter-effect@latest/dist/core.js"></script>
    
    <script src="{% static 'js/menuC.js' %}"></script>

    <script>
      function validateForm() {
        const name = document.getElementById("name").value.trim();
        const email = document.getElementById("email").value.trim();
        const phone = document.getElementById("phone").value.trim();
        const description = document.getElementById("description").value.trim();

        if (name === "") {
          alert("Por favor, ingrese su nombre.");
        } else if (email === "") {
          alert("Por favor, ingrese su correo electrónico.");
        } else if (!validateEmail(email)) {
          alert("Por favor, ingrese un correo electrónico válido.");
        } else if (phone === "") {
          alert("Por favor, ingrese su número de teléfono.");
        } else if (!validatePhone(phone)) {
          alert("Por favor, ingrese un número de teléfono válido.");
        } else if (description === "") {
          alert("Por favor, ingrese una descripción.");
        } else {
          alert("Formulario enviado correctamente.");
        }
      }

      function validateEmail(email) {
        // Expresión regular para validar un correo electrónico.
        const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        return regex.test(email);
      }

      function validatePhone(phone) {
        // Expresión regular para validar un número de teléfono.
        const regex = /^\d{10}$/;
        return regex.test(phone);
      }
    </script>
<!--MAPA-->
<section class="page-section bg-color-contacto mapa">
<div class="container">
    <div class="text-center">
        <h2 class="section-heading text-uppercase textContac">Contáctanos </h2>
        <h3 class="section-subheading color-let">Envíanos un mensaje</h3>
    </div>
  <div class="row">
    <div class="col-md p-3">
      <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1385.865976340312!2d-74.14459635412035!3d4.623263584088366!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e3f9ea1709219c9%3A0x6f406235e52b6547!2sAUTOSERVICIO%20RAIGOZA!5e0!3m2!1ses!2sco!4v1676855615927!5m2!1ses!2sco" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
    </div>
    <!--FORMULARIO-->
    <div class="col-md p-3" id="contactanos">
      
      <form>
        <div class="form-group">
          <label for="name">Nombres</label>
          <input type="text" class="form-control" id="name" name="name"></input>
        </div>

        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" class="form-control" id="email" name="email"></input>
        </div>

        <div class="form-group">
          <label for="phone">Teléfono</label>
          <input type="tel" class="form-control" id="phone" name="phone"></input>
        </div>

        <div class="form-group">
          <label for="description">Mensaje</label>
          <textarea id="description"class="form-control" placeholder="Escribe tu mensaje aquí" id="description" rows="3"></textarea>
        </div>

        <div class="text-center">
            <button class="btnenviarContac" id="submitButton" type="button" onclick="validateForm()">enviar</button>
        </div>  
        </form>        
        </div>                      
    </div> 
  </div>

</section>
{% endblock %}

<!--PIE DE PAGINA-->
<footer class="piepagina" >
    <div class="grupo1" id="nosotros">
  
      <div class="box">
        <figure>
          <a href="#">
            <img src="{% static 'img/images/logo.png'%}" alt=""></img>
          </a>
        </figure>
      </div>
      <div class="box">
        <h2>SOBRE NOSOTROS</h2>
        <p>Nuestra empresa fue fundada en el año 2016, después de hacer realidad la idea de formar una empresa y fomentar empleos directos que contribuyan al buen desarrollo de una sociedad Colombiana más justa y competitiva. Nuestra misión ha sido implementar procesos modernos de comercialización de acuerdo con el mercado y por último, nuestra visión es mantener nuestra calidad y expandirnos a otros horizontes para servirle de una manera más cómoda a nuestros clientes.
        </p>
      </div>
      <div class="box">
        <h2>SIGUENOS</h2>
        <div class="redsocial">
          <a href="https://www.facebook.com/groups/1586837975002924/" class="fab fa-facebook"></a>
          <a href="https://www.instagram.com/senacomunica/" class="fab fa-instagram"></a>
          <a href="https://twitter.com/SENAComunica" class="fab fa-twitter"></a>
          <a href="https://business.whatsapp.com/" class="fab fa-whatsapp"></a>
        </div>
      </div>
    </div>
    <div class="grupo2">
      <small> 2023 <b>Distribuidora Occidental</b> - Todos los Derechos Reservados.</small>
    </div>
</footer>
</body>
</html>